// Pure domain logic for multi-project / multi-board (v1): safe parsers,
// ID validation, and role-capability functions. No storage, no network, no
// D1 -- see the multi-project implementation plan, Task 1, for scope.
//
// House style follows app/board-model.ts: parsers accept `unknown` and
// narrow defensively; malformed input is rejected rather than coerced into
// a half-valid object.

import type {
  BoardMeta,
  Project,
  ProjectRole,
  ProjectSummary,
  ResourceStatus,
  WorkspaceRole,
} from "./types";

const MAX_RESOURCE_NAME_LENGTH = 80;

const WORKSPACE_ROLES: readonly WorkspaceRole[] = ["owner", "admin", "member"];
const PROJECT_ROLES: readonly ProjectRole[] = ["manager", "contributor", "viewer"];
const RESOURCE_STATUSES: readonly ResourceStatus[] = ["active", "archived"];

/** IDs that only ever exist in local (unsynced) storage -- see
 * docs/superpowers/plans/2026-07-24-multi-project-multi-board-v1.md Task 2.
 * These must never be sent to the Worker API as if they were real,
 * server-issued Project/Board IDs. */
export const LOCAL_LEGACY_PROJECT_ID = "local:legacy-project";
export const LOCAL_LEGACY_BOARD_ID = "local:legacy-board";

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// ---------------------------------------------------------------------------
// Role / status guards
// ---------------------------------------------------------------------------

export function isWorkspaceRole(value: unknown): value is WorkspaceRole {
  return WORKSPACE_ROLES.includes(value as WorkspaceRole);
}

export function isProjectRole(value: unknown): value is ProjectRole {
  return PROJECT_ROLES.includes(value as ProjectRole);
}

export function isResourceStatus(value: unknown): value is ResourceStatus {
  return RESOURCE_STATUSES.includes(value as ResourceStatus);
}

// ---------------------------------------------------------------------------
// ID validation
// ---------------------------------------------------------------------------

/** Accepts any well-formed UUID string (any version/variant), whether it was
 * generated by the client or the server -- see design spec §8: "所有 ID 使用
 * client/server 都可產生的 UUID 字串". */
export function isUuid(value: unknown): value is string {
  return typeof value === "string" && UUID_PATTERN.test(value);
}

/** True only for the known local-only placeholder IDs used before a legacy
 * Project/Board has been migrated to the server. */
export function isLocalPlaceholderId(value: unknown): value is string {
  return value === LOCAL_LEGACY_PROJECT_ID || value === LOCAL_LEGACY_BOARD_ID;
}

/** The validator API/network boundaries must call before trusting an ID as
 * a real, server-issued resource identifier. Local placeholder IDs always
 * fail this check, even if the placeholder format ever changes. */
export function isServerResourceId(value: unknown): value is string {
  return isUuid(value) && !isLocalPlaceholderId(value);
}

// ---------------------------------------------------------------------------
// Name normalization
// ---------------------------------------------------------------------------

export type NormalizedResourceName = {
  /** Trimmed, display-ready name (1-80 characters). */
  name: string;
  /** Case-folded key for duplicate-name comparisons. */
  key: string;
};

/** Trims a candidate Project/Board name, rejects blank or >80-character
 * (post-trim) values, and produces a case-folded comparison key. */
export function normalizeResourceName(value: unknown): NormalizedResourceName | null {
  if (typeof value !== "string") {
    return null;
  }
  const name = value.trim();
  if (!name || name.length > MAX_RESOURCE_NAME_LENGTH) {
    return null;
  }
  return {
    name,
    key: name.normalize("NFKC").toLocaleLowerCase("en-US"),
  };
}

// ---------------------------------------------------------------------------
// Project role capability matrix (design spec §7.2)
// ---------------------------------------------------------------------------
//
//   能力                                | manager | contributor | viewer
//   查看 Project 與 Board / summary/Log |    ✓    |      ✓      |   ✓
//   新增／編輯／移動 Card                |    ✓    |      ✓      |   -
//   新增／下載／移除 Attachment          |  ✓ full |   ✓ full    | 僅下載
//   建立／重新命名 Board                 |    ✓    |      -      |   -
//   封存／還原 Board                     |    ✓    |      -      |   -
//   修改 Project 名稱                    |    ✓    |      -      |   -
//   管理 Project members 與角色          |    ✓    |      -      |   -
//   封存／還原 Project                   |    ✓    |      -      |   -
//
// Every function below is defensive at runtime: an unrecognized role
// string (e.g. a WorkspaceRole value leaking across the authorization axis)
// is denied every capability rather than falling through to a default
// permission.

/** View a Project, its Boards, project summary/monthly report, and its
 * Activity Log. All three Project roles can read. */
export function canReadProject(role: ProjectRole): boolean {
  return isProjectRole(role);
}

/** Add, edit, or move Cards within a Board. Viewer can never mutate. */
export function canEditBoard(role: ProjectRole): boolean {
  return isProjectRole(role) && role !== "viewer";
}

/** Upload or remove an Attachment. Viewer may only download (see
 * canDownloadAttachment). */
export function canWriteAttachment(role: ProjectRole): boolean {
  return isProjectRole(role) && role !== "viewer";
}

/** Download an Attachment. All three Project roles can download. */
export function canDownloadAttachment(role: ProjectRole): boolean {
  return isProjectRole(role);
}

/** Manager-only gate for Project-level management: renaming/archiving the
 * Project, managing members, and creating/renaming/archiving Boards. This
 * is the single source of truth the manager-only wrappers below delegate
 * to. */
export function canManageProject(role: ProjectRole): boolean {
  return isProjectRole(role) && role === "manager";
}

/** Create a new Board within the Project. */
export function canCreateBoard(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Rename an existing Board. */
export function canRenameBoard(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Archive a Board. */
export function canArchiveBoard(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Restore an archived Board. */
export function canRestoreBoard(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Rename the Project itself. */
export function canRenameProject(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Add/remove Project members or change their role. Contributor explicitly
 * has no membership-management capability. */
export function canManageMembers(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Archive the Project itself. Contributor explicitly has no archive
 * capability. */
export function canArchiveProject(role: ProjectRole): boolean {
  return canManageProject(role);
}

/** Restore an archived Project. */
export function canRestoreProject(role: ProjectRole): boolean {
  return canManageProject(role);
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

type ArchiveFields = { archivedAt: string | null; archivedBy: string | null };

/** Archive metadata must agree with `status`: an active resource carries no
 * archive metadata, and an archived resource must carry both a timestamp
 * and the user who archived it. Returns null (reject) if they disagree. */
function parseArchiveFields(
  status: ResourceStatus,
  archivedAtRaw: unknown,
  archivedByRaw: unknown,
): ArchiveFields | null {
  if (status === "active") {
    return archivedAtRaw === null && archivedByRaw === null
      ? { archivedAt: null, archivedBy: null }
      : null;
  }

  if (typeof archivedAtRaw !== "string" || !archivedAtRaw || !isUuid(archivedByRaw)) {
    return null;
  }
  return { archivedAt: archivedAtRaw, archivedBy: archivedByRaw };
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

/** Safely parses a single `Project` from untrusted JSON. Returns null for
 * any malformed shape (missing/wrong-typed fields, blank/overlong name,
 * non-UUID or placeholder IDs, or archive metadata inconsistent with
 * `status`) rather than producing a half-valid object. */
export function parseProject(value: unknown): Project | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const raw = value as Record<string, unknown>;
  const normalizedName = normalizeResourceName(raw.name);

  if (
    !isUuid(raw.id) ||
    !isUuid(raw.workspaceId) ||
    !normalizedName ||
    !isResourceStatus(raw.status) ||
    !isUuid(raw.createdBy) ||
    !isNonEmptyString(raw.createdAt) ||
    !isNonEmptyString(raw.updatedAt)
  ) {
    return null;
  }

  const archive = parseArchiveFields(raw.status, raw.archivedAt, raw.archivedBy);
  if (!archive) {
    return null;
  }

  return {
    id: raw.id,
    workspaceId: raw.workspaceId,
    name: normalizedName.name,
    status: raw.status,
    createdBy: raw.createdBy,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
    archivedAt: archive.archivedAt,
    archivedBy: archive.archivedBy,
  };
}

/** Safely parses a single `BoardMeta` from untrusted JSON. Board *content*
 * (`BoardState`) is never part of this shape -- see design spec §8.4 -- so
 * an extra `data` property on the input is simply ignored. */
export function parseBoardMeta(value: unknown): BoardMeta | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const raw = value as Record<string, unknown>;
  const normalizedName = normalizeResourceName(raw.name);

  if (
    !isUuid(raw.id) ||
    !isUuid(raw.projectId) ||
    !normalizedName ||
    !isResourceStatus(raw.status) ||
    !Number.isInteger(raw.revision) ||
    (raw.revision as number) < 0 ||
    !isUuid(raw.createdBy) ||
    !isNonEmptyString(raw.createdAt) ||
    !isNonEmptyString(raw.updatedAt)
  ) {
    return null;
  }

  const archive = parseArchiveFields(raw.status, raw.archivedAt, raw.archivedBy);
  if (!archive) {
    return null;
  }

  return {
    id: raw.id,
    projectId: raw.projectId,
    name: normalizedName.name,
    status: raw.status,
    revision: raw.revision as number,
    createdBy: raw.createdBy,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
    archivedAt: archive.archivedAt,
    archivedBy: archive.archivedBy,
  };
}

function parseProjectSummary(value: unknown): ProjectSummary | null {
  if (!value || typeof value !== "object") {
    return null;
  }
  const raw = value as Record<string, unknown>;
  const normalizedName = normalizeResourceName(raw.name);

  if (
    !isUuid(raw.id) ||
    !normalizedName ||
    !isResourceStatus(raw.status) ||
    !isProjectRole(raw.myRole) ||
    !Number.isInteger(raw.activeBoardCount) ||
    (raw.activeBoardCount as number) < 0
  ) {
    return null;
  }

  if (raw.lastActivityAt !== null && !isNonEmptyString(raw.lastActivityAt)) {
    return null;
  }

  return {
    id: raw.id,
    name: normalizedName.name,
    status: raw.status,
    myRole: raw.myRole,
    activeBoardCount: raw.activeBoardCount as number,
    lastActivityAt: raw.lastActivityAt === null ? null : raw.lastActivityAt,
  };
}

/** Safely parses `GET /projects` -- the caller's own memberships as
 * `ProjectSummary[]` (design spec §7.3, §10.1). Malformed entries are
 * dropped individually rather than failing the whole list, matching the
 * defensive-normalization style used elsewhere in this codebase (e.g.
 * `normalizeCards` in app/board-model.ts). */
export function parseProjectList(value: unknown): ProjectSummary[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const result: ProjectSummary[] = [];
  for (const item of value) {
    const parsed = parseProjectSummary(item);
    if (parsed) {
      result.push(parsed);
    }
  }
  return result;
}
